### ISSUE TITLE
I want to tweak this for codechef.com

### ISSUE THREAD

**Issue by rkscodes** [LordLava/codeforces-darktheme#3]
Could you guide me how I should go about tweaking this script so that it works on codechef.com too. I use both the sites and would love to make code chef dark like this too.

**Comment by LordLava** [comment]
You can find tutorials on the internet and google. You need to modify the javascript and css to be for codechef and whatever they called their html elements and so on. Perhaps if I start using codechef in the future I'll make a codechef version.

> Could you guide me how I should go about tweaking this script so that it works on codechef.com too. I use both the sites and would love to make code chef dark like this too.
